version: "3.8"
services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - ./MyGitrepo/edtechConfigs:/mountedRepo
    networks:
      - myNetWork
  
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - myNetWork
  
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - myNetWork
  
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports: 
      - "9000:9000"
    depends_on: 
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - myNetWork
  
  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    ports: 
      - "8100:8100"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - myNetWork

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - myNetWork
      


networks:
 myNetWork:
  